// seed.js
require("dotenv").config();
const mongoose = require("mongoose");
const Category = require("./models/Category");
const Product = require("./models/Product");

const data = async () => {
  try {
    // 1) Connect to MongoDB
    await mongoose.connect(process.env.MONGO_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });

    // 2) Clear existing collections
    await Category.deleteMany();
    await Product.deleteMany();
    // (Optionally) await User.deleteMany();

    // 3) Create categories
    const [catMen, catWomen, catKids, catSneak] = await Category.create([
      { name: "Men's Apparel", slug: "mens-apparel" },
      { name: "Women's Apparel", slug: "womens-apparel" },
      { name: "Kids (3+)", slug: "kids-apparel" },
      { name: "Sneakers", slug: "sneakers" },
    ]);
    // 6) Create sample products (10+ per category)
    const products = [
      // Men's Apparel
      {
        title: "Olive Crewneck Tee",
        slug: "olive-crewneck-tee",
        description: "100% cotton, relaxed fit.",
        price: 25.0,
        discountPrice: 20.0,
        sku: "TEE-OLIVE-001",
        category: catMen._id,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Olive Green", "Black"],
        images: ["https://picsum.photos/200/300"],
        stock: 100,
        isFeatured: true,
        tags: ["t-shirt", "crewneck"],
      },
      {
        title: "Black Slim Chinos",
        slug: "black-slim-chinos",
        description: "Stretch cotton with slim-leg cut.",
        price: 45.0,
        sku: "CHINO-BLK-002",
        category: catMen._id,
        sizes: ["30", "32", "34", "36"],
        colors: ["Black"],
        images: ["https://picsum.photos/200/300"],
        stock: 80,
        tags: ["pants", "chinos"],
      },
      {
        title: "Navy Oxford Shirt",
        slug: "navy-oxford-shirt",
        description: "Button-down Oxford cloth shirt.",
        price: 35.0,
        sku: "SHIRT-NAVY-003",
        category: catMen._id,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Navy"],
        images: ["https://picsum.photos/200/300"],
        stock: 60,
        tags: ["shirt", "formal"],
      },
      {
        title: "Grey Wool Blend Sweater",
        slug: "grey-wool-blend-sweater",
        description: "Warm wool blend knit sweater.",
        price: 55.0,
        discountPrice: 50.0,
        sku: "SWEATER-GRY-004",
        category: catMen._id,
        sizes: ["M", "L", "XL"],
        colors: ["Grey"],
        images: ["https://picsum.photos/200/300"],
        stock: 40,
        tags: ["sweater", "winter"],
      },
      {
        title: "Denim Jacket",
        slug: "denim-jacket",
        description: "Classic blue denim with button closure.",
        price: 75.0,
        sku: "JKT-DNM-005",
        category: catMen._id,
        sizes: ["M", "L", "XL"],
        colors: ["Blue Denim"],
        images: ["https://picsum.photos/200/300"],
        stock: 30,
        tags: ["jacket"],
      },
      {
        title: "White Polo Shirt",
        slug: "white-polo-shirt",
        description: "Breathable piqué cotton.",
        price: 30.0,
        sku: "POLO-WHT-006",
        category: catMen._id,
        sizes: ["S", "M", "L", "XL"],
        colors: ["White"],
        images: ["https://picsum.photos/200/300"],
        stock: 90,
        tags: ["polo"],
      },
      {
        title: "Charcoal Joggers",
        slug: "charcoal-joggers",
        description: "Soft jersey joggers with tapered leg.",
        price: 40.0,
        sku: "JOGGER-CHR-007",
        category: catMen._id,
        sizes: ["M", "L", "XL"],
        colors: ["Charcoal"],
        images: ["https://picsum.photos/200/300"],
        stock: 70,
        tags: ["joggers", "casual"],
      },
      {
        title: "Striped V-Neck Tee",
        slug: "striped-v-neck-tee",
        description: "Lightweight cotton with subtle stripes.",
        price: 22.0,
        sku: "TEE-STRP-008",
        category: catMen._id,
        sizes: ["S", "M", "L", "XL"],
        colors: ["White/Black"],
        images: ["https://picsum.photos/200/300"],
        stock: 110,
        tags: ["t-shirt"],
      },
      {
        title: "Brown Leather Belt",
        slug: "brown-leather-belt",
        description: "Genuine leather with metal buckle.",
        price: 20.0,
        sku: "BELT-BRW-009",
        category: catMen._id,
        sizes: ["S", "M", "L"],
        colors: ["Brown"],
        images: ["https://picsum.photos/200/300"],
        stock: 150,
        tags: ["accessory"],
      },
      {
        title: "Navy Swim Shorts",
        slug: "navy-swim-shorts",
        description: "Quick-dry fabric, mesh lining.",
        price: 28.0,
        sku: "SWIM-NAV-010",
        category: catMen._id,
        sizes: ["M", "L", "XL"],
        colors: ["Navy"],
        images: ["https://picsum.photos/200/300"],
        stock: 85,
        tags: ["swimwear"],
      },

      // Women's Apparel
      {
        title: "Floral Summer Dress",
        slug: "floral-summer-dress",
        description: "Lightweight chiffon maxi dress.",
        price: 50.0,
        sku: "DRS-FLR-101",
        category: catWomen._id,
        sizes: ["S", "M", "L"],
        colors: ["Floral Print"],
        images: ["https://picsum.photos/200/300"],
        stock: 65,
        tags: ["dress"],
      },
      {
        title: "Black Skinny Jeans",
        slug: "black-skinny-jeans",
        description: "High-rise stretch denim.",
        price: 45.0,
        discountPrice: 38.0,
        sku: "JEANS-BLK-102",
        category: catWomen._id,
        sizes: ["25", "26", "27", "28", "29"],
        colors: ["Black"],
        images: ["https://picsum.photos/200/300"],
        stock: 70,
        tags: ["jeans"],
      },
      {
        title: "White Button-Up Blouse",
        slug: "white-button-up-blouse",
        description: "Silky polyester blend.",
        price: 35.0,
        sku: "BLSE-WHT-103",
        category: catWomen._id,
        sizes: ["S", "M", "L"],
        colors: ["White"],
        images: ["https://picsum.photos/200/300"],
        stock: 80,
        tags: ["blouse"],
      },
      {
        title: "Pink Knit Cardigan",
        slug: "pink-knit-cardigan",
        description: "Soft acrylic knit cardigan.",
        price: 40.0,
        sku: "CARDI-PNK-104",
        category: catWomen._id,
        sizes: ["S", "M", "L"],
        colors: ["Pink"],
        images: ["https://picsum.photos/200/300"],
        stock: 55,
        tags: ["cardigan"],
      },
      {
        title: "Blue Denim Skirt",
        slug: "blue-denim-skirt",
        description: "A-line mini skirt.",
        price: 30.0,
        sku: "SKIRT-DNM-105",
        category: catWomen._id,
        sizes: ["S", "M", "L"],
        colors: ["Blue Denim"],
        images: ["https://picsum.photos/200/300"],
        stock: 60,
        tags: ["skirt"],
      },
      {
        title: "Red Wrap Top",
        slug: "red-wrap-top",
        description: "V-neck wrap style.",
        price: 28.0,
        sku: "TOP-RDP-106",
        category: catWomen._id,
        sizes: ["S", "M", "L"],
        colors: ["Red"],
        images: ["https://picsum.photos/200/300"],
        stock: 75,
        tags: ["top"],
      },
      {
        title: "Grey Yoga Leggings",
        slug: "grey-yoga-leggings",
        description: "Moisture-wicking fabric.",
        price: 32.0,
        sku: "LEGGY-GRY-107",
        category: catWomen._id,
        sizes: ["S", "M", "L"],
        colors: ["Grey"],
        images: ["https://picsum.photos/200/300"],
        stock: 90,
        tags: ["leggings"],
      },
      {
        title: "Black Leather Handbag",
        slug: "handbag-black-leather",
        description: "Faux leather shoulder bag.",
        price: 60.0,
        sku: "BAG-BLK-108",
        category: catWomen._id,
        colors: ["Black"],
        images: ["https://picsum.photos/200/300"],
        stock: 45,
        tags: ["accessory"],
      },
      {
        title: "White Lace Camisole",
        slug: "white-lace-camisole",
        description: "Delicate lace trim.",
        price: 22.0,
        sku: "CAMI-WHT-109",
        category: catWomen._id,
        sizes: ["S", "M", "L"],
        images: ["https://picsum.photos/200/300"],
        stock: 85,
        tags: ["top"],
      },
      {
        title: "Beige Linen Shorts",
        slug: "beige-linen-shorts",
        description: "Breathable linen blend.",
        price: 29.0,
        sku: "SHORT-BEG-110",
        category: catWomen._id,
        sizes: ["S", "M", "L"],
        colors: ["Beige"],
        images: ["https://picsum.photos/200/300"],
        stock: 70,
        tags: ["shorts"],
      },

      // Kids Apparel
      {
        title: "Kids Pink Tutu Dress",
        slug: "kids-pink-tutu-dress",
        description: "Tulle skirt with cotton bodice.",
        price: 30.0,
        sku: "KDRS-PNK-201",
        category: catKids._id,
        sizes: ["3", "4", "5", "6"],
        images: ["https://picsum.photos/200/300"],
        stock: 50,
        tags: ["dress"],
      },
      {
        title: "Blue Graphic Tee",
        slug: "kids-blue-graphic-tee",
        description: "100% cotton with fun print.",
        price: 18.0,
        sku: "KTEE-BLU-202",
        category: catKids._id,
        sizes: ["3", "4", "5", "6"],
        colors: ["Blue"],
        images: ["https://picsum.photos/200/300"],
        stock: 80,
      },
      {
        title: "Kids Camo Joggers",
        slug: "kids-camo-joggers",
        description: "Soft jersey with camo print.",
        price: 22.0,
        sku: "KJOG-CAM-203",
        category: catKids._id,
        sizes: ["3", "4", "5", "6"],
        images: ["https://picsum.photos/200/300"],
        stock: 60,
      },
      {
        title: "Yellow Raincoat",
        slug: "kids-yellow-raincoat",
        description: "Waterproof with hood.",
        price: 35.0,
        sku: "COAT-YEL-204",
        category: catKids._id,
        sizes: ["3", "4", "5", "6"],
        colors: ["Yellow"],
        images: ["https://picsum.photos/200/300"],
        stock: 40,
      },
      {
        title: "Green Polo Shirt",
        slug: "kids-green-polo-shirt",
        description: "Cotton piqué polo.",
        price: 20.0,
        sku: "KPolo-GRN-205",
        category: catKids._id,
        sizes: ["3", "4", "5", "6"],
        colors: ["Green"],
        images: ["https://picsum.photos/200/300"],
        stock: 75,
      },
      {
        title: "Grey Fleece Hoodie",
        slug: "kids-grey-fleece-hoodie",
        description: "Soft fleece, front pocket.",
        price: 28.0,
        sku: "KHOO-GRY-206",
        category: catKids._id,
        sizes: ["3", "4", "5", "6"],
        images: ["https://picsum.photos/200/300"],
        stock: 65,
      },
      {
        title: "Multi-Color Swim Set",
        slug: "kids-multicolor-swim-set",
        description: "Two-piece swimwear set.",
        price: 25.0,
        sku: "KSWIM-MC-207",
        category: catKids._id,
        images: ["https://picsum.photos/200/300"],
        stock: 55,
      },
      {
        title: "Kids Denim Jacket",
        slug: "kids-denim-jacket",
        description: "Lightweight denim jacket.",
        price: 45.0,
        sku: "KJKT-DNM-208",
        category: catKids._id,
        sizes: ["3", "4", "5", "6"],
        images: ["https://picsum.photos/200/300"],
        stock: 50,
      },
      {
        title: "Blue Baseball Cap",
        slug: "kids-blue-baseball-cap",
        description: "Adjustable strap.",
        price: 12.0,
        sku: "KCAP-BLU-209",
        category: catKids._id,
        images: ["https://picsum.photos/200/300"],
        stock: 100,
      },
      {
        title: "Kids Cargo Shorts",
        slug: "kids-cargo-shorts",
        description: "Multiple pockets, durable.",
        price: 24.0,
        sku: "KSHORT-CAR-210",
        category: catKids._id,
        sizes: ["3", "4", "5", "6"],
        images: ["https://picsum.photos/200/300"],
        stock: 70,
      },

      // Sneakers
      {
        title: "White Minimalist Sneaker",
        slug: "white-minimalist-sneaker",
        description: "Leather upper, rubber sole.",
        price: 60.0,
        sku: "SNK-WHITE-001",
        category: catSneak._id,
        sizes: ["UK6", "UK7", "UK8", "UK9"],
        colors: ["White"],
        images: ["https://picsum.photos/200/300"],
        stock: 200,
        isFeatured: true,
      },
      {
        title: "Black High-Top Sneaker",
        slug: "black-high-top-sneaker",
        description: "Canvas upper with ankle support.",
        price: 65.0,
        sku: "SNK-BLK-002",
        category: catSneak._id,
        sizes: ["UK6", "UK7", "UK8", "UK9", "UK10"],
        colors: ["Black"],
        images: ["https://picsum.photos/200/300"],
        stock: 120,
      },
      {
        title: "Grey Mesh Running Shoe",
        slug: "grey-mesh-running-shoe",
        description: "Lightweight breathable mesh.",
        price: 70.0,
        sku: "SNK-GRY-003",
        category: catSneak._id,
        sizes: ["UK6", "UK7", "UK8", "UK9"],
        images: ["https://picsum.photos/200/300"],
        stock: 150,
      },
      {
        title: "Blue Retro Sneaker",
        slug: "blue-retro-sneaker",
        description: "Suede detail with retro styling.",
        price: 75.0,
        sku: "SNK-BLU-004",
        category: catSneak._id,
        sizes: ["UK6", "UK7", "UK8", "UK9"],
        images: ["https://picsum.photos/200/300"],
        stock: 90,
      },
      {
        title: "Red Slip-On Sneaker",
        slug: "red-slip-on-sneaker",
        description: "Elastic gore for easy on/off.",
        price: 55.0,
        sku: "SNK-RD-005",
        category: catSneak._id,
        sizes: ["UK6", "UK7", "UK8", "UK9"],
        colors: ["Red"],
        images: ["https://picsum.photos/200/300"],
        stock: 110,
      },
      {
        title: "Green Trail Running Shoe",
        slug: "green-trail-running-shoe",
        description: "Rugged outsole for trail grip.",
        price: 80.0,
        sku: "SNK-GRN-006",
        category: catSneak._id,
        sizes: ["UK6", "UK7", "UK8", "UK9"],
        images: ["https://picsum.photos/200/300"],
        stock: 70,
      },
      {
        title: "Pink Canvas Sneaker",
        slug: "pink-canvas-sneaker",
        description: "Casual canvas for everyday wear.",
        price: 50.0,
        sku: "SNK-PNK-007",
        category: catSneak._id,
        sizes: ["UK6", "UK7", "UK8", "UK9"],
        colors: ["Pink"],
        images: ["https://picsum.photos/200/300"],
        stock: 95,
      },
      {
        title: "Yellow Skate Sneaker",
        slug: "yellow-skate-sneaker",
        description: "Durable suede and rubber sole.",
        price: 68.0,
        sku: "SNK-YEL-008",
        category: catSneak._id,
        sizes: ["UK6", "UK7", "UK8", "UK9"],
        colors: ["Yellow"],
        images: ["https://picsum.photos/200/300"],
        stock: 85,
      },
      {
        title: "Purple Lightweight Sneaker",
        slug: "purple-lightweight-sneaker",
        description: "Breathable upper for comfort.",
        price: 62.0,
        sku: "SNK-PUR-009",
        category: catSneak._id,
        sizes: ["UK6", "UK7", "UK8", "UK9"],
        colors: ["Purple"],
        images: ["https://picsum.photos/200/300"],
        stock: 130,
      },
      {
        title: "Brown Hiking Sneaker",
        slug: "brown-hiking-sneaker",
        description: "Sturdy design for outdoor adventures.",
        price: 90.0,
        sku: "SNK-BRN-010",
        category: catSneak._id,
        sizes: ["UK6", "UK7", "UK8", "UK9"],
        colors: ["Brown"],
        images: ["https://picsum.photos/200/300"],
        stock: 60,
      },
    ];

    // 7) Insert products
    await Product.create(products);

    console.log("✅ Data Seeded Successfully");
    process.exit(0);
  } catch (err) {
    console.error("❌ Seed Error:", err);
    process.exit(1);
  }
};

data();
